.\" Copyright (C), 2012  Shin'ichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rscparse 1 2012-08-06 RENKEI-VPE
.SH NAME
rscparse \- parser for resource files for RENKEI-VPE
.SH SYNOPSIS
\fBrscparse\fR <command> [ \fB\fIoptions\fB\fR ] <input_file>
.SH DESCRIPTION
This command parses CSV-formatted resource files into RENKEI-VPE\'s YAML-formatted resource files.
.PP
The \fI<command>\fR is a name of a subcommand of rscparse command.
Run \'rscparse help\' to see the detail of the usage.
\" .SH OPTIONS
\" .SH FILES
\" .SH "SEE ALSO"
\" .SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
