.\" Copyright (C), 2012  Shinichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rvpeuser 1 2012-08-08 RENKEI-VPE
.SH NAME
rvpeuser \- show and edit user information
.SH SYNOPSIS
\fBrvpeuser\fR <command> [ \fB\fIargs\fB\fR ] [ \fB\fIoptions\fB\fR ]
.SH DESCRIPTION
This command shows and edits information of users who use RENKEI-VPE.
The administrator of RENKEI-VPE can \fBcreate\fR, \fBdelete\fR, \fBenable\fR, \fBdisable\fR and \fBshow\fR specified users and \fBlist\fR all users.
The administrator can also change \fBpassword\fR of users and \fBgrant/rob permissions\fR to use specified zones.
A user can see his/her information.
.PP
The \fI<command>\fR is a name of a subcommand of rvpeuser command.
Run \'rvpeuser help\' to see the detail of the usage.
.PP
.\".SH FILES
.SH "SEE ALSO"
\fIrvpehost\fP(1),
\fIrvpeimage\fP(1),
\fIrvpelease\fP(1),
\fIrvpevm\fP(1),
\fIrvpevmtype\fP(1),
\fIrvpevnet\fP(1),
\fIrvpezone\fP(1),
.PP
.\".SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
