.\" Copyright (C), 2012  Shin'ichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rvpezone 1 2012-05-24 RENKEI-VPE
.SH NAME
rvpezone \- manipulate zones
.SH SYNOPSIS
\fBrvpezone\fR <command> [ \fB\fIargs\fB\fR ] [ \fB\fIoptions\fB\fR ]
.SH DESCRIPTION
This command manipulate zones where VM runs.
The administrator can 1)create/delete zones, 2)add/remove physical hosts to/from zones and 3)add/remove virtual networks to/from zones.
Users can show information about zones, such as list of physical hosts, list of virtual networks.
.PP
The \fI<command>\fR is a name of a subcommand of rvpezone command.
Run 'rvpezone help' to see the detail of the usage.
\" .SH OPTIONS
\" .SH FILES
.SH "SEE ALSO"
\fIrvpehost\fP(1),
\fIrvpeimage\fP(1),
\fIrvpelease\fP(1),
\fIrvpeuser\fP(1),
\fIrvpevm\fP(1),
\fIrvpevmtype\fP(1),
\fIrvpevnet\fP(1),
\" .SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
