.\" Copyright (C), 2012  Shin'ichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rvpelease 1 2012-08-08 RENKEI-VPE
.SH NAME
rvpelease \- manage the assignment of IP address
.SH SYNOPSIS
\fBrvpelease\fR <command> [ \fB\fIargs\fB\fR ] [ \fB\fIoptions\fB\fR ]
.SH DESCRIPTION
This command manages and shows assignments of IP address to users.
The administrator can assing/release IP addresses to/from users.
The user can just see his/her IP address assginment.
.PP
The \fI<command>\fR is a name of a subcommand of rvpelease command.
Run \'rvpelease help\' to see the detail of the usage.
\" .SH OPTIONS
\" .SH FILES
.SH "SEE ALSO"
\fIrvpehost\fP(1),
\fIrvpeimage\fP(1),
\fIrvpeuser\fP(1),
\fIrvpevm\fP(1),
\fIrvpevmtype\fP(1),
\fIrvpevnet\fP(1),
\fIrvpezone\fP(1),
\" .SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
