.\" Copyright (C), 2012  Shin'ichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rvpehost 1 2012-05-24 RENKEI-VPE
.SH NAME
rvpehost \- show and edit physical host information
.SH SYNOPSIS
\fBrvpehost\fR <command> [ \fB\fIargs\fB\fR ] [ \fB\fIoptions\fB\fR ]
.SH DESCRIPTION
This command shows and enables/disables to use the specified physical hosts which are registered as VM hosting servers.
.PP
The \fI<command>\fR is a name of a subcommand of rvpehost command.
Run 'rvpehost help' to see the detail of the usage.
\" .SH OPTIONS
\" .SH FILES
.SH "SEE ALSO"
\fIrvpeimage\fP(1),
\fIrvpelease\fP(1),
\fIrvpeuser\fP(1),
\fIrvpevm\fP(1),
\fIrvpevmtype\fP(1),
\fIrvpevnet\fP(1),
\fIrvpezone\fP(1),
\" .SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
