.\" Copyright (C), 2012  Shin'ichiro Takizawa
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH rvpevmtype 1 2012-05-24 RENKEI-VPE
.SH NAME
rvpevmtype \- manipulate virtual machine type configuration
.SH SYNOPSIS
\fBrvpevmtype\fR <command> [ \fB\fIargs\fB\fR ] [ \fB\fIoptions\fB\fR ]
.SH DESCRIPTION
This command manipulate VM type configuration.
VM type containts 1)name, 2)number of CPUs, 3)amount of memory and 4)its short description.
The administrator can create/delete VM type and the user can show them.
.PP
The \fI<command>\fR is a name of a subcommand of rvpevmtype command.
Run 'rvpevmtype help' to see the detail of the usage.
\" .SH OPTIONS
\" .SH FILES
.SH "SEE ALSO"
\fIrvpehost\fP(1),
\fIrvpeimage\fP(1),
\fIrvpelease\fP(1),
\fIrvpeuser\fP(1),
\fIrvpevm\fP(1),
\fIrvpevnet\fP(1),
\fIrvpezone\fP(1),
\" .SH BUGS
.SH AUTHOR
Shinichiro Takizawa <takizawa@gsic.titech.ac.jp>
.\" Local Variables:
.\" mode: nroff
.\" End:
