require 'renkei-vpe-server/one_client'
require 'rexml/document'

module RenkeiVPE
  class User < ServerRole

    # return information about this user.
    # +session+   string that represents user session
    # +id+        id of the user
    # +return[0]+ true or false whenever is successful or not
    # +return[1]+ if an error occurs this is error message,
    #             if successful this is the string with the information
    #             about the user
    def info(session, id)
      authenticate(session, true) do
        rc = call_one_xmlrpc('one.user.info', session, id)
        return rc unless rc[0]

        doc = REXML::Document.new(rc[1])
        doc.each_element('/USER') do |e|
          User.insert_zones_to_onexml(e)
        end

        return [true, doc.to_s]
      end
    end

    # It inserts user's available zones to an xml generated by one.
    # +e+ REXML::Element that represents one putput
    def self.insert_zones_to_onexml(e)
      # get user name
      name_e = e.get_elements('NAME')[0]
      raise "User is not found: User[#{id}]" unless name_e
      name = name_e.get_text

      # get zone info and insert it to rc[1]
      zones = Users.find('zones', "name='#{name}'")[0]
      zones_e = REXML::Element.new('ZONES')
      zones_e.add(REXML::Text.new(zones))
      e.add(zones_e)
    end

  end
end

# Local Variables:
# mode: Ruby
# coding: utf-8
# indent-tabs-mode: nil
# End:
