#!/bin/bash
#
# rvpe    rvpe runs This shell script starts/stops rvpe.
#
# chkconfig: 2345 98 1
# description: rvpe starts/stops/statuses RENKEI-VPE.

. /etc/profile.d/one.sh
. /etc/profile.d/renkei-vpe.sh

RETVAL=0

# Command path
SU=/bin/su
GFARM2FS=/usr/bin/gfarm2fs
FUSERMOUNT=/usr/bin/fusermount

# Parameters for OpenNebula
ONEADMIN=popadmin
ONE_PID_FILE=$ONE_LOCATION/var/oned.pid
IMAGE_REPO=$ONE_LOCATION/var/images

# Parameters for Renkei-VPE
RVPEADMIN=popadmin
GF_LOCAL_PATH=/work/one_images
GF_N_REPLICAS=3


# Check over-write of RENKEI-VPE parameters
_update_by_user_value() {
    # $1: parameter name
    # $2: current value
    VAL_LINE=`grep -v '^#' $RVPE_LOCATION/etc/rvped.conf | grep $1`
    VAL=`echo $VAL_LINE | cut -d ':' -f2 | tr -d '[:blank:]'`
    if [ $VAL ]; then
        echo $VAL
    else
        echo $2
    fi
}
GF_LOCAL_PATH=`_update_by_user_value 'gfarm_local_path' $GF_LOCAL_PATH`
GF_N_REPLICAS=`_update_by_user_value 'gfarm_replica_count' $GF_N_REPLICAS`


_status() {
    # check status of OpenNebula
    if [ ! -f $ONE_PID_FILE ]; then
        return 1
    fi
    if [ ! -d /proc/`cat $ONE_PID_FILE` ]; then
        return 1
    fi

    # check status of RENKEI-VPE
    $SU - $RVPEADMIN -c '\
      source /etc/profile.d/one.sh; \
      source /etc/profile.d/renkei-vpe.sh; \
      $RVPE_LOCATION/sbin/rvped status 1>/dev/null 2>/dev/null'
    if [ ! $? -eq 0 ]; then
        return 2
    fi

    return 0
}

start() {
    _status
    if [ $? -eq 0 ]; then
        echo 'RENKEI-VPE is already running.'
        RETVAL=1
        return
    fi

    # mount gfarm
    $SU - $ONEADMIN -c "\
      $GFARM2FS -o ncopy=$GF_N_REPLICAS \
                -o modules=subdir -o subdir=$GF_LOCAL_PATH $IMAGE_REPO"
    if [ ! $? -eq 0 ]; then
        echo 'Failed to start RENKEI-VPE: gfarm2fs failed to mount'
        RETVAL=1
        return
    fi

    # start OpenNebula
    $SU - $ONEADMIN -c '\
      source /etc/profile.d/one.sh; \
      $ONE_LOCATION/bin/one -b start'
    if [ ! $? -eq 0 ]; then
        echo 'Failed to start RENKEI-VPE: OpenNebula failed to start'
        RETVAL=1
        $SU - $ONEADMIN -c "$FUSERMOUNT -u $IMAGE_REPO"
        return
    fi

    # start RENKEI-VPE
    $SU - $RVPEADMIN -c '\
      source /etc/profile.d/one.sh; \
      source /etc/profile.d/renkei-vpe.sh; \
      $RVPE_LOCATION/sbin/rvped start'
    if [ ! $? -eq 0 ]; then
        echo 'Failed to start RENKEI-VPE.'
        RETVAL=1
        $SU - $ONEADMIN -c '\
          source /etc/profile.d/one.sh; \
          $ONE_LOCATION/bin/one stop'
        $SU - $ONEADMIN -c "$FUSERMOUNT -u $IMAGE_REPO"
        return
    fi

    RETVAL=0
}

stop() {
    _status
    if [ ! $? -eq 0 ]; then
        echo 'RENKEI-VPE is not running.'
        RETVAL=1
        return
    fi

    # stop RENKEI-VPE
    $SU - $RVPEADMIN -c '\
      source /etc/profile.d/one.sh; \
      source /etc/profile.d/renkei-vpe.sh; \
      $RVPE_LOCATION/sbin/rvped stop'
    if [ ! $? -eq 0 ]; then
        echo 'Failed to stop RENKEI-VPE.'
        RETVAL=1
    fi

    # stop OpenNebula
    $SU - $ONEADMIN -c '\
      source /etc/profile.d/one.sh; \
      $ONE_LOCATION/bin/one stop'
    if [ ! $? -eq 0 ]; then
        echo 'Failed to stop RENKEI-VPE: OpenNebula failed to stop'
        RETVAL=1
    fi

    # unmount gfarm
    $SU - $ONEADMIN -c "$FUSERMOUNT -u $IMAGE_REPO"
    if [ ! $? -eq 0 ]; then
        echo 'Failed to stop RENKEI-VPE: fusermount failed to umount gfarm'
        RETVAL=1
    fi

    RETVAL=0
}

status() {
    _status
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        PID=`cat $RVPE_LOCATION/var/rvped.pid`
        echo "RENKEI-VPE (pid $PID) is running..."
    elif [ $RETVAL -eq 1 ]; then
        echo "RENKEI-PVE is not running: OpenNebula is not running"
    elif [ $RETVAL -eq 2 ]; then
        echo "RENKEI-PVE is not running."
    else
        echo "Unknown status."
    fi
}


if [ ! $UID == 0 ]; then
    echo 'Run as root'
    exit 1
fi

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=1
esac

exit $RETVAL
